### ISSUE TITLE
I do have a find method in employee.cs that searches by employee id

### ISSUE THREAD

**Issue by RubyBe** [andrewniekamp/seattle_health_clinic#10]
@yichiang , @andrewniekamp 

// a method to find an employee using the employee id
    public static Employee Find(int Id)
    {
      SqlConnection conn = DB.Connection();
      conn.Open();
      SqlCommand cmd = new SqlCommand("SELECT \* FROM employees WHERE id = @EmployeeId;", conn);
      SqlParameter employeeIdParameter = new SqlParameter();
      employeeIdParameter.ParameterName = "@EmployeeId";
      employeeIdParameter.Value = Id.ToString();
      cmd.Parameters.Add(employeeIdParameter);
      SqlDataReader rdr = cmd.ExecuteReader();
      int foundEmployeeId = 0;
      string foundEmployeeFirstName = null;
      string foundEmployeeLastName = null;
      while(rdr.Read())
      {
        foundEmployeeId = rdr.GetInt32(0);
        foundEmployeeFirstName = rdr.GetString(1);
        foundEmployeeLastName = rdr.GetString(2);
      }
      Employee foundEmployee = new Employee(foundEmployeeFirstName, foundEmployeeLastName, foundEmployeeId);

```
  if (rdr != null)
  {
    rdr.Close();
  }
  if (conn != null)
  {
    conn.Close();
  }
  return foundEmployee;
}
```

**Comment by andrewniekamp** [comment]
Thank you!
